### ISSUE TITLE
invalid argument

### ISSUE THREAD

**Issue by pcd70** [DominiLux/amdgpu-pro-fans#2]
pascal@pcd70:~/amdgpu-pro-fans$ sudo ./amdgpu-pro-fans.sh -s 100
* AMDGPU-PRO-FANS *
error: invalid arguments
usage: ./amdgpu-pro-fans.sh [-h] for help...

Ubuntu16.04
Radeon R9 380 (driver amdgpu-pro driver installed)

I dont know what to do

**Comment by DominiLux** [comment]
Let me check it out.  It's probably just a parsing error on my part.  I just made the commits in the development branch the other day but haven’t had time to test it.  I should have a fix in a few hours.  I'm copying it over to my R9 380 6GPU rig as we speak to see what might be going on.

**Comment by DominiLux** [comment]
This issue has been corrrected.  It is now fully compatible with all R8, R9, and RX Sereis graphics cards.  It's been fully tested with all cards in these series on Ubuntu 16.04.  I merged to update to the master branch.  Please use git update for revisions to take effect in your system.
