### ISSUE TITLE
Run multiple times?

### ISSUE THREAD

**Issue by Overcon** [DominiLux/amdgpu-pro-fans#8]
Can you run this script multiple times? First time I ran it it gave me an error about the on board video not having a fan, but it set the other cards fans to what percent I told it. 

But on subsequent runs it doesn't return errors, no changes to the fan speed, nothing.

**Comment by DominiLux** [comment]
As long as you run it as sudo user. This script was initially an experiment to accomplish what others said was impossible at the time. I thrive on the impossible. I have deprecated this project as I am in the testing phase for a full GP control server written in C++.  It offers temperature control, manually setting fan speeds, GPU under and over clocking, Memory under and over clocking, voltage control, BIOS dump and BIOS flash. Oh and a JSON api for full remote control and monitoring of all your GPUs. I've been working on it for some time now and look forward to releasing it.

**Comment by Overcon** [comment]
Very cool, I am looking JUST for a program like that! I await with high anticipation! Thanks for your work!

**Comment by DominiLux** [comment]
A lot of people are. Its not just for mining but for managing large computational clusters and monitoring GPU health remotely for large data center deployment. I think I will use the BAD license but I'm still debating on what would be best for larger scale corporations such as Google.  My hope is that my contribution will help AMD gain market share thereby forcing nVidia to slash prices on their overpriced products. $500 for a GPU is rediculious when you calculate the actual cost to produce them.

**Comment by DominiLux** [comment]
BSD license
